### ISSUE TITLE
Editor To-Do

### ISSUE THREAD

**Issue by AlexNisnevich** [AlexNisnevich/untrusted#9]
## Should Probably Do
- [ ] Allow multi-line deletion, and handle it intelligently
## Would Be Cool
- [ ] Mouseover help for known functions
## Possibly Too Much Work
- [ ] Switch from CodeMirror to Ace editor (http://ace.c9.io/), which has live syntax checking support (!!!)
  - OR take a look at how Ace does it (https://github.com/ajaxorg/ace/wiki/Syntax-validation) and see if we can mimic it
